name: Deployment Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  changes:
    outputs:
      functions: ${{ steps.changes.outputs.functions }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: json
          filters: |
            changed: 'lambda/*/**'
      - id: changes
        env:
          changed: ${{ steps.filter.outputs.changed_files }}
        run: |
          functions="$( echo $changed | \
            jq -r '.[]' | \
            cut -d'/' -f1,2 | \
            sort | \
            uniq | \
            jq -s -R -c 'split("\n") | \
            map(select(. != "" and . != "layer01" and .!= "layer02"))' )"
          echo "functions=${functions}" >> $GITHUB_OUTPUT

  build:
    needs: changes
    if: needs.changes.outputs.functions != '[]'
    strategy:
      matrix:
        function: ${{ fromJSON(needs.changes.outputs.functions) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "node.jsならビルドするよー ${{ matrix.function }}"
        if: ${{ hashFiles(format('{0}/{1}', matrix.function, 'package.json')) != '' }}
        working-directory: ${{ matrix.function }}
      - run: echo "デプロイするよー ${{ matrix.function }}"
